[project]
name = "na-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.1.0",
    "nornir>=3.4.1",
    "pip>=24.3.1",
    "pyats>=24.11",
]
